monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_input.usb-Yamaha_Corporation_Steinberg_UR22mkII-00.HiFi__Line2__source"
      }
    ]
    actions = {
      update-props = {
        node.nick = "UR22mkII • Input 1 ★ MIC (use this)"
        node.description = "UR22mkII • Input 1 ★ MIC (use this)"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.usb-Yamaha_Corporation_Steinberg_UR22mkII-00.HiFi__Line3__source"
      }
    ]
    actions = {
      update-props = {
        node.nick = "UR22mkII • Input 2"
        node.description = "UR22mkII • Input 2"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-Yamaha_Corporation_Steinberg_UR22mkII-00.HiFi__Line1__sink"
      }
    ]
    actions = {
      update-props = {
        node.nick = "UR22mkII • Stereo Output"
        node.description = "UR22mkII • Stereo Output"
      }
    }
  }
]
